language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

matrix:
  fast_finish: true

script:
  - nosetests tests --with-coverage --cover-package=backcast --cover-erase --cover-html --rednose
